import React from 'react';
import { render, screen } from '@testing-library/react';
import App from './App';
jest.mock('./components/ai/AiAssistHost', () => ({ __esModule: true, default: ({ children }: any) => <>{children}</> }));
jest.mock('./components/ai/AiAssistPage', () => ({ __esModule: true, default: () => <div>AiAssistPage</div> }));
jest.mock('./components/analytics/AnalyticsStudioPage', () => ({ __esModule: true, default: () => <div>AnalyticsStudioPage</div> }));
jest.mock('./components/Header', () => ({ __esModule: true, default: () => <div>Header</div> }));
jest.mock('./components/Sidebar', () => ({ __esModule: true, default: () => <div>Sidebar</div> }));
jest.mock('./components/LoginPage', () => ({ __esModule: true, default: () => <div>LoginPage</div> }));
jest.mock('./components/ProjectMonitoringApp', () => ({ __esModule: true, default: () => <div>ProjectMonitoringApp</div> }));
jest.mock('./components/ProjectLocationDashboard', () => ({ __esModule: true, default: () => <div>ProjectLocationDashboard</div> }));
jest.mock('./components/ExpenseMonitoring', () => ({ __esModule: true, default: () => <div>ExpenseMonitoring</div> }));
jest.mock('./components/LiquidationFormPage', () => ({ __esModule: true, default: () => <div>LiquidationFormPage</div> }));
jest.mock('./components/CAFormPage', () => ({ __esModule: true, default: () => <div>CAFormPage</div> }));
jest.mock('./components/ClientsPage', () => ({ __esModule: true, default: () => <div>ClientsPage</div> }));
jest.mock('./components/MaterialRequestFormPage', () => ({ __esModule: true, default: () => <div>MaterialRequestFormPage</div> }));
jest.mock('./components/DeliveryPage', () => ({ __esModule: true, default: () => <div>DeliveryPage</div> }));
jest.mock('./components/SuppliersPage', () => ({ __esModule: true, default: () => <div>SuppliersPage</div> }));
jest.mock('./components/PurchaseOrderPage', () => ({ __esModule: true, default: () => <div>PurchaseOrderPage</div> }));
jest.mock('./components/EstimatesPage', () => ({ __esModule: true, default: () => <div>EstimatesPage</div> }));
jest.mock('./components/ReportsPage', () => ({ __esModule: true, default: () => <div>ReportsPage</div> }));
jest.mock('./components/UtilitiesPage', () => ({ __esModule: true, default: () => <div>UtilitiesPage</div> }));
jest.mock('./components/EHSPage', () => ({ __esModule: true, default: () => <div>EHSPage</div> }));
jest.mock('./components/IDGeneratorPage', () => ({ __esModule: true, default: () => <div>IDGeneratorPage</div> }));
jest.mock('./components/AcknowledgementReceiptPage', () => ({ __esModule: true, default: () => <div>AcknowledgementReceiptPage</div> }));
jest.mock('./components/SystemBackupsPage', () => ({ __esModule: true, default: () => <div>SystemBackupsPage</div> }));
jest.mock('./components/DirectLaborPage', () => ({ __esModule: true, default: () => <div>DirectLaborPage</div> }));
jest.mock('./components/UserApprovalsPage', () => ({ __esModule: true, default: () => <div>UserApprovalsPage</div> }));
jest.mock('./components/UsersPage', () => ({ __esModule: true, default: () => <div>UsersPage</div> }));
jest.mock('./components/InvestmentTrackerPage', () => ({ __esModule: true, default: () => <div>InvestmentTrackerPage</div> }));
jest.mock('./components/CollectionsDashboard', () => ({ __esModule: true, default: () => <div>CollectionsDashboard</div> }));
jest.mock('./components/payroll/PayrollDashboard', () => ({ __esModule: true, default: () => <div>PayrollDashboard</div> }));
jest.mock('./components/payroll/PayrollGuard', () => ({ __esModule: true, default: ({ children }: any) => <>{children}</> }));
jest.mock('./components/finance/FinanceHomePage', () => ({ __esModule: true, default: () => <div>FinanceHomePage</div> }));
jest.mock('./components/ReimbursementDashboard', () => ({ __esModule: true, default: () => <div>ReimbursementDashboard</div> }));
jest.mock('./components/finance/ProjectExpenseReport', () => ({ __esModule: true, default: () => <div>ProjectExpenseReport</div> }));
jest.mock('./components/OverheadExpensesPage', () => ({ __esModule: true, default: () => <div>OverheadExpensesPage</div> }));
jest.mock('./components/finance/CompanyPnLPage', () => ({ __esModule: true, default: () => <div>CompanyPnLPage</div> }));
jest.mock('./components/finance/TaxFilerLedgerPage', () => ({ __esModule: true, default: () => <div>TaxFilerLedgerPage</div> }));
jest.mock('./components/finance/SalesEwtRegisterPage', () => ({ __esModule: true, default: () => <div>SalesEwtRegisterPage</div> }));
jest.mock('./components/finance/soa/SoaDashboardPage', () => ({ __esModule: true, default: () => <div>SoaDashboardPage</div> }));
jest.mock('./components/finance/soa/SoaDetailView', () => ({ __esModule: true, default: () => <div>SoaDetailView</div> }));
jest.mock('./components/sales/SalesHomePage', () => ({ __esModule: true, default: () => <div>SalesHomePage</div> }));
jest.mock('./components/employee/EmployeePortalHome', () => ({ __esModule: true, default: () => <div>EmployeePortalHome</div> }));
jest.mock('./components/employee/DTRPage', () => ({ __esModule: true, default: () => <div>DTRPage</div> }));
jest.mock('./components/employee/ClockPage', () => ({ __esModule: true, default: () => <div>ClockPage</div> }));
jest.mock('./components/employee/EmployeePayslipPage', () => ({ __esModule: true, default: () => <div>EmployeePayslipPage</div> }));
jest.mock('./components/employee/EmployeeServiceReportPage', () => ({ __esModule: true, default: () => <div>EmployeeServiceReportPage</div> }));
jest.mock('./components/calcsheet/CalcsheetProjects', () => ({ __esModule: true, default: () => <div>CalcsheetProjects</div> }));
jest.mock('./components/calcsheet/CalcsheetLegacyImport', () => ({ __esModule: true, default: () => <div>CalcsheetLegacyImport</div> }));
jest.mock('./components/calcsheet/CalcsheetProjectDetail', () => ({ __esModule: true, default: () => <div>CalcsheetProjectDetail</div> }));
jest.mock('./components/calcsheet/CalcsheetQuotationEditor', () => ({ __esModule: true, default: () => <div>CalcsheetQuotationEditor</div> }));
jest.mock('./components/calcsheet/CalcsheetCompareView', () => ({ __esModule: true, default: () => <div>CalcsheetCompareView</div> }));
jest.mock('./components/calcsheet/CalcsheetProjectSchedule', () => ({ __esModule: true, default: () => <div>CalcsheetProjectSchedule</div> }));
jest.mock('./components/ProjectSchedulePage', () => ({ __esModule: true, default: () => <div>ProjectSchedulePage</div> }));
jest.mock('./components/calcsheet/CalcsheetClients', () => ({ __esModule: true, default: () => <div>CalcsheetClients</div> }));
jest.mock('./components/calcsheet/CalcsheetPresets', () => ({ __esModule: true, default: () => <div>CalcsheetPresets</div> }));
jest.mock('./components/pricelists/PricelistBrowser', () => ({ __esModule: true, default: () => <div>PricelistBrowser</div> }));
jest.mock('./components/ScanPage', () => ({ __esModule: true, default: () => <div>ScanPage</div> }));
jest.mock('./contexts/AuthContext', () => ({ AuthProvider: ({ children }: any) => <>{children}</>, useAuth: () => ({ isAuthenticated: true, isLoading: false, user: { role: 'superadmin' } }) }));
jest.mock('./contexts/OneDriveAuthContext', () => ({ OneDriveAuthProvider: ({ children }: any) => <>{children}</> }));
jest.mock('./store/quotationStore', () => ({ useQuotationStore: jest.fn() }));
test.each([
  ['/finance/payroll', 'PayrollDashboard'],
  ['/finance/reimbursements', 'ReimbursementDashboard'],
  ['/finance/investment-tracker', 'InvestmentTrackerPage'],
])('%s keeps the shared header and sidebar', (path, page) => {
  window.history.replaceState({}, '', path);
  render(<App />);
  expect(screen.getByText(page)).toBeInTheDocument();
  expect(screen.getByText('Header')).toBeInTheDocument();
  expect(screen.getByText('Sidebar')).toBeInTheDocument();
});
